appName: ray-mlops-demo
runId: "dbdd5f5"

image:
  repository: harbor.morpheus.test/mlops/ray-mlops-demo
  tag: "dbdd5f5"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

job:
  entrypoint: "python -m src.train"
  shutdownAfterJobFinishes: false
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0

ray:
  version: "2.40.0"

head:
  cpu: "1"
  memory: "2Gi"

worker:
  replicas: 1
  cpu: "1"
  memory: "2Gi"

mlflow:
  trackingUri: http://mlflow.mlflow.svc.cluster.local
  experimentName: ray-mlops-demo

s3:
  endpointUrl: http://minio.minio.svc.cluster.local:9000
  bucket: ray
  region: ap-northeast-2
  secretName: ""

env:
  runNamePrefix: ray-mlops-demo

commonLabels:
  app.kubernetes.io/part-of: mlops-training
  app.kubernetes.io/component: ray-mlops-demo

httproute:
  enabled: true
  hostname: ray-mlops-demo.morpheus.test
  gatewayName: nginx-gateway
  gatewayNamespace: nginx-gateway
  sectionName: https
