{{- if .Values.secrets.airflowDb.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.airflowDb.name }}
  namespace: {{ .Values.secrets.airflowDb.namespace }}
type: Opaque
stringData:
  connection: {{ .Values.secrets.airflowDb.connection | quote }}
---
{{- end }}
{{- if .Values.secrets.gitCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gitCredentials.name }}
  namespace: {{ .Values.secrets.gitCredentials.namespace }}
type: Opaque
stringData:
  GIT_SYNC_USERNAME: {{ .Values.secrets.gitCredentials.username | quote }}
  GIT_SYNC_PASSWORD: {{ .Values.secrets.gitCredentials.password | quote }}
  GITSYNC_USERNAME: {{ .Values.secrets.gitCredentials.username | quote }}
  GITSYNC_PASSWORD: {{ .Values.secrets.gitCredentials.password | quote }}
---
{{- end }}
{{- if .Values.secrets.kubeconfig.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kubeconfig.name }}
  namespace: {{ .Values.secrets.kubeconfig.namespace }}
type: Opaque
stringData:
  config: |
{{ .Values.secrets.kubeconfig.config | indent 4 }}
{{- end }}
