{{- if .Values.httproute.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-dashboard" (.Values.appName | toString) | trunc 63 | trimSuffix "-" | quote }}
  labels:
{{ include "mlops-demo.labels" . | indent 4 }}
{{ toYaml .Values.commonLabels | indent 4 }}
spec:
  type: ClusterIP
  selector:
    ray-dashboard: {{ printf "%s-%s" (.Values.appName | toString) (.Values.runId | toString) | trunc 63 | trimSuffix "-" | quote }}
  ports:
    - name: dashboard
      port: 8265
      targetPort: 8265
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-dashboard" (.Values.appName | toString) | trunc 63 | trimSuffix "-" | quote }}
  labels:
{{ include "mlops-demo.labels" . | indent 4 }}
{{ toYaml .Values.commonLabels | indent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gatewayName | quote }}
      namespace: {{ .Values.httproute.gatewayNamespace | quote }}
      sectionName: {{ .Values.httproute.sectionName | quote }}
  hostnames:
    - {{ .Values.httproute.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ printf "%s-dashboard" (.Values.appName | toString) | trunc 63 | trimSuffix "-" | quote }}
          port: 8265
{{- end }}
