apiVersion: v2
name: postgres-operator
description: Morpheus wrapper chart for StradVision Postgres Operator installation.
type: application
version: 0.1.0
appVersion: 1.15.1
dependencies:
  - name: postgres-operator
    alias: postgresOperator
    version: 1.15.1
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
