apiVersion: v2
name: mlflow
description: Morpheus wrapper chart for StradVision MLflow installation.
type: application
version: 0.1.0
appVersion: 3.7.0
dependencies:
  - name: mlflow
    alias: mlflow
    version: 1.8.1
    repository: https://community-charts.github.io/helm-charts
