{{- if .Values.githubAppSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.githubAppSecret.name }}
  namespace: {{ .Values.githubAppSecret.namespace }}
type: Opaque
stringData:
  github_app_id: {{ .Values.githubAppSecret.appId | quote }}
  github_app_installation_id: {{ .Values.githubAppSecret.installationId | quote }}
  github_app_private_key: |
{{ .Values.githubAppSecret.privateKey | indent 4 }}
{{- end }}
