{{- if .Values.gatewayClass.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
---
{{- end }}
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: {{ .Values.gateway.hostname | quote }}
      allowedRoutes:
        namespaces:
          from: All
{{- if .Values.gateway.enableHttps }}
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.gateway.hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName }}
      allowedRoutes:
        namespaces:
          from: All
{{- end }}
{{- end }}
