{{- if .Values.s3Secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3Secret.name }}
  namespace: {{ .Values.s3Secret.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3Secret.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Secret.secretAccessKey | quote }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.s3Secret.endpointUrl | quote }}
{{- end }}
